# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bcf1b915b47725d909c1ebe06aa188e05726a28f896a2356512271d89ac1e6b5d01e310667ab8f9fe3bf3515b2f3887165895634d7d11baf43add5d3f91fa5e3

test:
  secret_key_base: d68179f8d8d5f94460437e08632787a2f445695891554f8a6dc7d177b09b52b077537bdbd7d859f172abf510d53e77bcc4fa6153297dc28db7fb0e3df64e4456

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
